docker_image: "nsls2/linux-anvil-cos7-x86_64:latest"
env_name: "py39"
conda_env_file: "env-py39.yml"
conda_binary: "mamba"
python_version: "3.9"
pkg_name: ""
pkg_version: ""
extra_packages: "mamba"
channels: "-c conda-forge"
